### testing for user controller

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"imran@gmail.com",
    "password":"2580123"
};

### Find a particular user

GET http://localhost:3000/auth/allUser


