### testing for user controller

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"adil@gmail.com",
    "password":"2580123"
}

### Find all user

GET http://localhost:3000/auth/allUser


### Find a specific user

GET http://localhost:3000/auth/2

### update a specific user

PUT http://localhost:3000/auth/3
Content-Type: application/json

{
    "password":"123456"
}


### Delete a specific user

DELETE http://localhost:3000/auth/1

